{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.home.ai;

  defaultProfiles = {
    default.settings = {
      # network = {
      #   allowLocalOutbound = true;
      # };
      filesystem = {
        allowWrite = ["." "/tmp"];
      };
    };
  };

  settingsForNixEnv = {
    "$schema" = "https://raw.githubusercontent.com/fencesandbox/fence/main/docs/schema/fence.schema.json";
    filesystem = {
      allowRead = ["/nix/store"];
      allowExecute = ["/nix/store"];
    };
  };

  finalProfiles = lib.mapAttrs' (name: entry: {
    inherit name;
    value = lib.my.deepMerge entry { settings = settingsForNixEnv; };
  }) cfg.harness.sandbox.profiles;
in
{
  options.my.home.ai.harness.sandbox = with lib; with lib.types; {
    enable = mkEnableOption "Whether to enable the AI harness sandbox";
    profiles = mkOption {
      type = attrsOf (submodule {
        options = {
          # path = mkOption {
          #   type = nullOr path;
          #   description = "A sandbox profile for the AI harness. This is generated by system";
          #   default = null;
          # };
          settings = mkOption {
            type = attrs;
            description = "Settings for the sandbox profile.";
          };
          default = mkEnableOption "Whether to set as default profile for the AI harness sandbox.";
        };
      });
      default = defaultProfiles;
    };
  };
  config = lib.mkIf (cfg.harness.enable && cfg.harness.sandbox.enable) {
    home.packages = with pkgs; [
      fence
    ];

    xdg.configFile = lib.mkMerge [
      (lib.mapAttrs' (name: entry: {
        name = "fence/${name}.json";
        value.text = builtins.toJSON entry.settings;
      }) finalProfiles)
      {
        # "fence/fence.json".source = builtins.toJSON (lib.filterAttrs (n: v: v.default) finalProfiles).settings;
      }
    ];
  };
}
