# JetBrains Central CLI, the loopback proxy behind JetBrains Air Gateway. It
# accepts requests from AI coding agents and injects JetBrains authentication
# on the way out, so agents reach JetBrains AI Platform with the account's AI
# credits instead of their own vendor key.
#
# Enabled here installs the package, declares the loopback listener port and
# keeps the proxy running as a user service. Login is deliberately left as a
# manual, interactive step: `central login` opens a browser for OAuth 2.0
# PKCE and mints tokens that are encrypted with the system keyring key, which
# a declarative build cannot do on the user's behalf.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.my.home.ai.gateways.jetbrainsCentral;

  centralBin = lib.getExe' pkgs.my.jetbrains-central-cli "central";

  # `central proxy start` does not simply fail when no login exists: with tokens
  # missing it opens a browser consent page on a loopback port and waits for the
  # redirect, which never arrives under a service manager. A unit that called it
  # unguarded would hang `systemctl --user start` instead of failing, and the
  # session would appear to have a stuck unit. The encrypted token file is the
  # only artifact that exists once login completed, so its absence is the check;
  # `tokens.enc.lock` is created on every run and cannot stand in for it.
  loginGuard = pkgs.writeShellApplication {
    name = "check-central-login";
    text = ''
      tokenFile="$HOME/.jetbrains-central/tokens.enc"
      if [ ! -s "$tokenFile" ]; then
        echo "jetbrains-central-gateway: not logged in to JetBrains Central." >&2
        echo "Run 'central login' interactively once; it needs a browser for OAuth 2.0 PKCE." >&2
        exit 1
      fi
    '';
  };
in
{
  options.my.home.ai.gateways.jetbrainsCentral = {
    enable = lib.mkEnableOption "Enable JetBrains Central CLI and run its local AI gateway proxy";

    port = lib.mkOption {
      type = lib.types.port;
      default = 19516;
      example = 19517;
      description = ''
        Port the gateway proxy listens on.

        Passed to the service as `WIRE_PROXY_PORT`, which upstream documents as
        taking precedence over the port persisted in
        `~/.jetbrains-central/config.json`. Agent wires are generated by
        `central add <agent>`, so changing this after an agent is wired requires
        re-running that command to repoint the agent.
      '';
    };

    extraEnv = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = lib.literalExpression ''
        {
          HTTP_PROXY = "http://corp.example:3128";
        }
      '';
      description = ''
        Extra environment variables for the `central` process.

        Scoped to the service, not exported into the session. Keep secrets out:
        tokens are encrypted with the system keyring key and the proxy reads them
        from its own data directory.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.my.jetbrains-central-cli ];

    # `central proxy start` forks the proxy into the background and exits, so
    # systemd never sees the long-running process. oneshot + RemainAfterExit
    # models that shape: the start command returns immediately while the proxy
    # it spawned keeps serving.
    systemd.user.services.jetbrains-central-gateway = {
      Unit = {
        Description = "JetBrains Central CLI gateway proxy";
        Documentation = [ "https://www.jetbrains.com/help/central-cli/" ];
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
      };

      Service = {
        Type = "oneshot";
        RemainAfterExit = true;

        Environment = [
          "WIRE_PROXY_PORT=${toString cfg.port}"
        ] ++ lib.mapAttrsToList (name: value: "${name}=${value}") cfg.extraEnv;

        # Fail fast and legibly when login has not happened yet, instead of
        # leaving the unit pending on a browser callback that cannot arrive.
        ExecStartPre = lib.getExe loginGuard;

        ExecStart = centralBin + " proxy start";
        ExecStop = centralBin + " proxy stop";

        # Stopping must never wedge the user session on an upstream hang.
        TimeoutStopSec = "30";
      };

      Install.WantedBy = [ "default.target" ];
    };

    assertions = [
      {
        assertion = cfg.port >= 1024;
        message = "my.home.ai.gateways.jetbrainsCentral.port: use an unprivileged port; the proxy is a per-user service";
      }
    ];
  };
}
